FROM jupyter/base-notebook

USER root

RUN apt-get update --yes

RUN apt-get install --yes --no-install-recommends \ 
    python3-dev default-libmysqlclient-dev build-essential pkg-config \
    gcc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install \
    ipython-sql \
    sqlalchemy==1.4.46 \
    mysqlclient

RUN pip install neo4j-driver